### ISSUE TITLE
Application refusing to start because target machine is refusing connections

### ISSUE THREAD

**Issue by chaosargate** [ShawnABurgess/tweetreader#5]
The tweetreader is failing to find new tweets because it can't connect to the Twitter API, which is a fatal error for the application. The errors are provided below.

```
Traceback (most recent call last):
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 334, in connect
    conn = self._new_conn()
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x04983DB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?screen_name=realdonaldtrump&count=200&include_rts=True&trim_user=False&exclude_replies=False&tweet_mode=extended (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04983DB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tweetReader.py", line 130, in <module>
    latest_tweet = find_last_tweet(api=api, screen_name=screen_name)
  File "tweetReader.py", line 69, in find_last_tweet
    timeline = api.GetUserTimeline(screen_name=screen_name, count=200)
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twitter\api.py", line 811, in GetUserTimeline
    resp = self._RequestUrl(url, 'GET', data=parameters)
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\twitter\api.py", line 4992, in _RequestUrl
    resp = self._session.get(url, auth=self.__auth, timeout=self._timeout, proxies=self.proxies)
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\lovan\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/user_timeline.json?screen_name=realdonaldtrump&count=200&include_rts=True&trim_user=False&exclude_replies=False&tweet_mode=extended (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04983DB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
```

**Comment by ShawnABurgess** [comment]
I think the local network is blocking access to the Twitter API. I will see about making the app handle this a bit cleaner and maybe use a proxy
